### ISSUE TITLE
Should we keep using PRs or switch to committing to master?

### ISSUE THREAD

**Issue by RomanEsin** [Activity-App/App#17]
This is quite a controversial thing, but would you commit directly to master branch or make a pull request so it gets reviewed?

**Comment by Kanishka3** [comment]
PR seems a better option - it somehow assures the quality of app!

**Comment by RomanEsin** [comment]
Yeah and it also gives us a topic to discuss the best implementation of something before actually merging it, because you can still push your commits too the PR and Merge it only all the changes.

**Comment by wfltaylor** [comment]
It seems the consensus is Pull Requests.
