### ISSUE TITLE
Activity Rings SPM 

### ISSUE THREAD

**Issue by Bubba8291** [Activity-App/App#9]
https://github.com/maxkonovalov/MKRingProgressView

**Comment by wfltaylor** [comment]
I'm not sure if this is necessary as drawing the rings shouldn't be too difficult.

**Comment by Priva28** [comment]
Yeah drawing rings is very easy in SwiftUI. I done it in my Playground lol

**Comment by Priva28** [comment]
I'm going to close this as the less dependencies, the better.
