### ISSUE TITLE
Create iCloud not signed in error page

### ISSUE THREAD

**Issue by wfltaylor** [Activity-App/App#96]
The app won't work without CloudKit, so this screen needs to explain that the app requires them to sign in to work.

**Comment by RomanEsin** [comment]
Is there some sort of popup In the onboarding screen or anywhere else that tells the user that they need to turn iCloud or something?

**Comment by wfltaylor** [comment]
> Is there some sort of popup In the onboarding screen or anywhere else that tells the user that they need to turn iCloud or something?

Apple doesn't provide anything by default.

**Comment by RomanEsin** [comment]
So there's nothing that user needs to tap to actually get iCloud to work in our app?

**Comment by wfltaylor** [comment]
They can give permission to let our app discover there friends, but that's not necessary for the app to function.

**Comment by RomanEsin** [comment]
# #103

**Comment by Jake-Short** [comment]
Added in #103
